### ISSUE TITLE
build: failed to build with nettle 4.0

### ISSUE THREAD

**Issue by fundawang** [FreeTDS/freetds#728]
When building freetds 1.5.17 with nettle 4.0 it produces following errors:
```
2026-05-10 04:11:21 In file included from challenge.c:43:
2026-05-10 04:11:21 ../../include/freetds/utils/md4.h: In function 'MD4Final':
2026-05-10 04:11:21 ../../include/freetds/utils/md4.h:41:32: warning: passing argument 2 of 'nettle_md4_digest' makes pointer from integer without a cast [-Wint-conversion]
2026-05-10 04:11:21    41 |         nettle_md4_digest(ctx, 16, digest);
2026-05-10 04:11:21       |                                ^~
2026-05-10 04:11:21       |                                |
2026-05-10 04:11:21       |                                int
2026-05-10 04:11:21 In file included from ../../include/freetds/utils/md4.h:25:
2026-05-10 04:11:21 /usr/include/nettle/md4.h:73:21: note: expected 'uint8_t *' {aka 'unsigned char *'} but argument is of type 'int'
2026-05-10 04:11:21    73 |            uint8_t *digest);
2026-05-10 04:11:21       |            ~~~~~~~~~^~~~~~
2026-05-10 04:11:21 ../../include/freetds/utils/md4.h:41:9: error: too many arguments to function 'nettle_md4_digest'
2026-05-10 04:11:21    41 |         nettle_md4_digest(ctx, 16, digest);
2026-05-10 04:11:21       |         ^~~~~~~~~~~~~~~~~
2026-05-10 04:11:21 /usr/include/nettle/md4.h:72:1: note: declared here
2026-05-10 04:11:21    72 | md4_digest(struct md4_ctx *ctx,
2026-05-10 04:11:21       | ^~~~~~~~~~
2026-05-10 04:11:21 make[4]: *** [Makefile:573: challenge.lo] Error 1
2026-05-10 04:11:21 make[4]: *** Waiting for unfinished jobs....
```
```
026-05-10 04:11:21 In file included from sec_negotiate.c:43:
2026-05-10 04:11:21 sec_negotiate_gnutls.h: In function 'sha1':
2026-05-10 04:11:21 sec_negotiate_gnutls.h:189:27: warning: passing argument 2 of 'nettle_sha1_digest' makes pointer from integer without a cast [-Wint-conversion]
2026-05-10 04:11:21   189 |         sha1_digest(&ctx, 20, hash);
2026-05-10 04:11:21       |                           ^~
2026-05-10 04:11:21       |                           |
2026-05-10 04:11:21       |                           int
2026-05-10 04:11:21 In file included from /usr/include/nettle/rsa.h:41,
2026-05-10 04:11:21                  from sec_negotiate_gnutls.h:36:
2026-05-10 04:11:21 /usr/include/nettle/sha1.h:75:22: note: expected 'uint8_t *' {aka 'unsigned char *'} but argument is of type 'int'
2026-05-10 04:11:21    75 |             uint8_t *digest);
2026-05-10 04:11:21       |             ~~~~~~~~~^~~~~~
2026-05-10 04:11:21 sec_negotiate_gnutls.h:189:9: error: too many arguments to function 'nettle_sha1_digest'
2026-05-10 04:11:21   189 |         sha1_digest(&ctx, 20, hash);
2026-05-10 04:11:21       |         ^~~~~~~~~~~
2026-05-10 04:11:21 /usr/include/nettle/sha1.h:74:1: note: declared here
2026-05-10 04:11:21    74 | sha1_digest(struct sha1_ctx *ctx,
2026-05-10 04:11:21       | ^~~~~~~~~~~
2026-05-10 04:11:21 make[4]: *** [Makefile:573: sec_negotiate.lo] Error 1
```

**Comment by freddy77** [comment]
Mumble... possibly I forgot to backport the fix from master.

**Comment by omribz156** [comment]
Hi, I can take a small paid pass at this if that helps.

The failure looks like a narrow nettle 4.0 API compatibility/backport issue: the 1.5.x code is still calling `nettle_md4_digest(ctx, 16, digest)` / `sha1_digest(&ctx, 20, hash)`, while nettle 4.0 exposes the shorter digest signatures shown in the build log.

I would keep the patch surgical:

- find the corresponding master fix/backport shape
- apply it to the affected 1.5.x code paths without changing unrelated auth code
- verify a nettle 4.0 build and include the exact build output in the PR

I use Codex for the legwork, but I’ll review the C diff manually and keep it small. I can do this for $150 after a verified build-fixing PR. If this should stay volunteer-only, no pressure.

**Comment by freddy77** [comment]
I already have a fix for this, tested with OpenMamba distro.

**Comment by fundawang** [comment]
Fixed in 1.5.18. Thanks.
