### ISSUE TITLE
Latest release candidate (R1_2RC1 ) failed to compile on macOS 10.15.5

### ISSUE THREAD

**Issue by hankinsoft** [FreeTDS/freetds#345]
`./autogen.sh --with-tdsver=7.3 --sysconfdir=/usr/local/etc --with-unixodbc=/usr/local/opt/unixodbc --with-openssl=/usr/local/opt/openssl@1.1 --enable-sybase-compat --enable-krb5 --enable-odbc-wide`

succeeds, but then `make` fails with:

```
Making all in .
  CC       mem.lo
  CC       token.lo
  CC       util.lo
  CC       login.lo
  CC       read.lo
  CC       write.lo
  CC       convert.lo
  CC       numeric.lo
  CC       config.lo
  CC       query.lo
  CC       iconv.lo
In file included from iconv.c:960:
charset_lookup.gperf:847:1: error: conflicting types for 'charset_lookup'
charset_lookup (str, len)
^
charset_lookup.gperf:4:36: note: previous declaration is here
static const struct charset_alias *charset_lookup(register const char *str, register size_t len);
                                   ^
1 error generated.
make[4]: *** [iconv.lo] Error 1
make[3]: *** [all-recursive] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
```

**Comment by freddy77** [comment]
I suspect the added declaration is not compatible in some cases. I also think the compilation should succeed using the packaged version (but it has to work also using git).

**Comment by freddy77** [comment]
Just to verify, can you post your `charset_lookup.h` and `charset_lookup.gperf` files?

**Comment by freddy77** [comment]
Fixed in `Branch-1_2`

**Comment by hankinsoft** [comment]
Thanks, that fixed it! PS - you should consider enabling [GitHub sponsors](https://github.com/sponsors). I would love to make a donation.
